### ISSUE TITLE
Undocumented limit

### ISSUE THREAD

**Issue by PatMyron** [awsdocs/aws-codepipeline-user-guide#24]
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/360#issuecomment-582156432
https://docs.aws.amazon.com/codepipeline/latest/userguide/limits.html
https://github.com/awsdocs/aws-codepipeline-user-guide/blob/master/doc_source/limits.md

**Comment by darlaker** [comment]
Hello, Thank you for adding this issue. I will fix this in the User Guide. Just to confirm, in the limits table where we document the maximum size limit of 1 kilobyte for the CloudFormation ParameterOverrides property, we should also add a limit of 1 kilobyte for CodeBuild environment variables property?

**Comment by darlaker** [comment]
Confirmed this CodePipeline behavior, and this is a limit for the action type configuration fields for each action. There is a 1000-character limit for the configuration fields (the fields under "configuration" are different depending on the action provider). Will add this limit to the Quotas table in the CodePipeline User Guide.

Also will add a note to the Variables section and the CodeBuild Action Structure Reference section advising that the use of variable syntax can cause the 1000-character limit for the configuration fields to be exceeded, such as in this CodeBuild action example, where a list of CodeBuild env variables containing CodePipeline output variable syntax can result in more characters quickly: 
```
"actionTypeId": {
            "category": "Test",
            "owner": "AWS",
            "version": "1",
            "provider": "CodeBuild"
          },
          "outputArtifacts": [
          ],
          "configuration": {
            "EnvironmentVariables": "[{\"name\": \"S3_VERSION_ID\", \"value\": \"#{SourceNamespace.VersionId}\", \"type\": \"PLAINTEXT\"}, {\"name\": \"S3_ETAG\", \"value\": \"#{ SourceNamespace.InvalidVariable}\", \"type\": \"PLAINTEXT\"}]"
          },
```

**Comment by darlaker** [comment]
This issue has been corrected. The key and value limits for the action configuration fields in CodePipeline (key limit is 50 characters and value limit is 1000 characters) have been documented in the User Guide here: https://docs.aws.amazon.com/codepipeline/latest/userguide/limits.html

To help notify that use of env variables, or output variables in general, in the configuration fields might lead to exceeding this limit, notes were added to the following: 
* The Variables topic here: https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-variables.html
* The CodeBuild action reference page here: https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodeBuild.html#action-reference-CodeBuild-config

Note text: "When you enter the name, value, and type for your environment variables configuration, especially if the environment variable contains CodePipeline output variable syntax, do not exceed the 1000-character limit for the configuration’s value field. A validation error is returned when this limit is exceeded."
