### ISSUE TITLE
AWS cloud: get github BRANCH name as an env var in codepipeline

### ISSUE THREAD

**Issue by gregbkr** [awsdocs/aws-codepipeline-user-guide#25]
Hi, 

I hope this is the right place to ask this question. If not please refer me where. Thanks.

I am trying to get github BRANCH name as an env var in codepipeline.

I display all ENV, but none got the right information (e.g. dev, master).

Env variables:

CODEBUILD_SOURCE_VERSIONgives me an ARN

CODEBUILD_WEBHOOK_BASE_REF is empty.

I got no CODEBUILD_WEBHOOK_* variable. Where should I get them?

I see these:
```
CODEBUILD_SOURCE_VERSION=arn:aws:s3:::codepipeline-hello/hello_dev/code/MCR1o4U.zip
DEP_VERSION=0.5.1
HOSTNAME=818ed2658298
PHP_SRC_DIR=/usr/src/php
GPG_KEY=E3FF2839C048B25C084DEBE9B26....
SBT_VERSION=1.2.8
LIBGIT2_PKG=https://rpmfind.net/linux/centos/7/extras/x86_64/Packages/libgit2-0.26.6-1.el7.x86_64.rpm
PHPPATH=/php
ANDROID_HOME=/usr/local/android-sdk-linux
ANDROID_SDK_EXTRAS=extras;android;m2repository extras;google;m2repository extras;google;google_play_services
POWERSHELL_VERSION=6.2.1
PHP_INI_DIR=/usr/local/etc/php
ANT_DOWNLOAD_SHA512=c1a9694c3018e248000ff6f46d48af85f537ef3935e0d5256543c58a240084c0aff5289fd9e94cbc40d5442f3cc43592398047f2548fded40d9882be2b40750d
AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=/v2/credentials/f80eef12-063d-4e34-894e-9ad9a3bb6793
GOLANG_13_VERSION=1.13.4
...
```
Thank you for your help!

I can see that someone found the answer, but I don't see how, and I can not put comment there... [get GitHub git branch for AWS CodeBuild](https://stackoverflow.com/questions/47657423/get-github-git-branch-for-aws-codebuild/60197636#60197636)

Thank you for your help! Greg.

**Comment by darlaker** [comment]
Hello Greg, Thank you so much for your question! Sorry you are experiencing this issue with the env variables. I am researching the answer to your question, and I will follow up soon.

**Comment by chase3c** [comment]
Are you familiar with the CodePipeline variables feature?  If your github repository is a source action of your pipeline then you can use this feature to pass the branch name as an environment variable into your codebuild action.

Conceptual overview of the feature:
https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-variables.html

Here is a walk through that passes the commit id as an environment variable into CodeBuild:
https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-variables.html

You could do the same thing with branch using the BranchName variable, to see a list of the variables that are included with a github action view the 'Output Variables' section here:
https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-GitHub.html#action-reference-GitHub-variables

**Comment by darlaker** [comment]
Thank you ccundiff! And thank you again gregbkr for your use case, which was the inspiration for our latest example for working with variables.

We have added a new example to the User Guide that walks through how to use CodeBuild environment variables to reference a BranchName output variable from your pipeline's GitHub source action: https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-variables.html#actions-variables-examples-env-branchname

Thank you again for your feedback and for helping us to improve the docs!
