### ISSUE TITLE
STOPPED status missing

### ISSUE THREAD

**Issue by tscully49** [awsdocs/aws-codepipeline-user-guide#42]
When I stop a codepipeline execution it has a status of "STOPPED" but I don't seem to see this in the documentation.  I also have trouble finding this status when trying to setup a notification event for the pipeline as well.  Not sure if this is also the case for codebuild stages/actions, but it seems like this should be added to this documentation and updated for the notification events for cloudwatch rules and eventbus rules.

**Comment by darlaker** [comment]
Hello, Thank you for your feedback on the User Guide. The STOPPED and STOPPING status descriptions are described in an overview here:  https://docs.aws.amazon.com/codepipeline/latest/userguide/concepts-how-it-works.html#concepts-how-it-works-stopping   And the procedure for stopping a pipeline is detailed here:  https://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-stop.html.  

To make this information easier to find, I have updated the pipeline execution, stage execution, and action execution concepts pages with the list of valid execution statuses and links to the API reference: 
https://docs.aws.amazon.com/codepipeline/latest/userguide/concepts.html#concepts-executions
https://docs.aws.amazon.com/codepipeline/latest/userguide/concepts.html#concepts-stage-executions
https://docs.aws.amazon.com/codepipeline/latest/userguide/concepts.html#concepts-action-executions 

Apologies for the frustration you experienced with creating notifications for pipelines with a STOPPED status. The event patterns and documentation reference information for cloudwatch events rules and eventbus rules will be updated soon. I will post here when that is available.

**Comment by tscully49** [comment]
That is great to hear, thank you!

**Comment by darlaker** [comment]
Thank you again for your feedback on this issue, and apologies for the delay on this update. The CodePipeline User Guide section for Monitoring with notifications through EventBridge/CloudWatch Events has been updated. The STOPPED and STOPPING statuses for pipeline and stage executions, the ABANDONED status for action executions, and event examples for all statuses have been added to the topic here: https://docs.aws.amazon.com/codepipeline/latest/userguide/detect-state-changes-cloudwatch-events.html .
