### ISSUE TITLE
Missing doc_source/update-github-action-connections.md

### ISSUE THREAD

**Issue by JoshCooley** [awsdocs/aws-codepipeline-user-guide#43]
The "Edit this page on GitHub" link at the bottom of
https://docs.aws.amazon.com/codepipeline/latest/userguide/update-github-action-connections.html
points to
https://github.com/awsdocs/aws-codepipeline-user-guide/tree/main/doc_source/update-github-action-connections.md,
which does not exist.

**Comment by darlaker** [comment]
Thank you for catching this broken link! Apologies for the new page not being available in the repo. The repo files are all the latest now. Thank you for letting us know and for your contribution to the docs!
