### ISSUE TITLE
Cross-Region source constraints are not applicable for all Source actions. S3 is an exception to the rule.

### ISSUE THREAD

**Issue by fabiodouek** [awsdocs/aws-codepipeline-user-guide#45]
The documentation mentions the following. Whereas the called out constraint is correct for Source types ECR and CodeCommit, it does not apply to cross region S3 buckets.

"You cannot create cross-Region actions for the following action types:

- Source actions
- Third-party actions
- Custom actions"

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
