### ISSUE TITLE
Undefined mode "ALWAYS_REPLACE"

### ISSUE THREAD

**Issue by tjohn123456** [awsdocs/aws-codepipeline-user-guide#46]
In the Output variables section of the doc https://github.com/awsdocs/aws-codepipeline-user-guide/blob/main/doc_source/action-reference-CloudFormation.md I see a mode "ALWAYS_REPLACE". But this mode is not defined as an available mode on top of the page under the "Action Modes" section. Is this a typo?

**Comment by darlaker** [comment]
Thank you for catching this error in the reference topic. Thank you for pointing out that "ALWAYS_REPLACE" is not a valid mode name. This has been corrected. The mode name has been changed to "CHANGE_SET_REPLACE" and the fix has been published here: https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CloudFormation.html#action-reference-CloudFormation-variables
