### ISSUE TITLE
AWS Lambda example to deploy CF is wrong

### ISSUE THREAD

**Issue by andreabedini** [awsdocs/aws-codepipeline-user-guide#5]
The Lambda example at this page 

https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-invoke-lambda-function.html

contains the following snippets

```
        if status not in ['CREATE_COMPLETE', 'ROLLBACK_COMPLETE', 'UPDATE_COMPLETE']:
            # If the CloudFormation stack is not in a state where
            # it can be updated again then fail the job right away.
            put_job_failure(job_id, 'Stack cannot be updated when status is: ' + status)
            return
```

but trying to update a stack with status `ROLLBACK_COMPLETE` ends up in

```
An error occurred (ValidationError) when calling the UpdateStack operation: Stack: XYZ is in ROLLBACK_COMPLETE state and can not be updated.
```

**Comment by darlaker** [comment]
Thank you for your comment and for bringing this issue to our attention. We are reviewing the solution and will post an update soon. Thank you!

**Comment by andreabedini** [comment]
Perhaps the code is meant to say `UPDATE_ROLLBACK_COMPLETE`.
