### ISSUE TITLE
Issue with aws-codepipeline during Control Tower Customization 

### ISSUE THREAD

**Issue by lokhandwalayusuf** [awsdocs/aws-codepipeline-user-guide#57]
We are doing Control Tower Customization via Code pipeline which is integrated with Internal BitBucket. 

Can someone please help on clarify below doubt?

For e.g. 
On Day 1, I have bitbucket code (manifest) for creating 2 IAM resources and 1 SCP resources, which I ran via Code pipeline and it deployed successfully 
On Day 2, I updated bitbucket code (manifest) and commented out 2 IAM resources (which I created on Day 1) and updated code for New SCP. **QUESTION IS** - if I run this pipeline, what happens to 2 IAM resources which i commented out? will they be ignored as i have commented out or they will be deleted? 

In our case, if we re-run same pipeline with few sections commented out, instead of being ignored, they seems to get deleted or messed up

I hope I was able to articulate my concern properly but if its confusing, let me know.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
