### ISSUE TITLE
"Amazon CloudWatch Events Prerequisites" no longer exists

### ISSUE THREAD

**Issue by mb-dev** [awsdocs/aws-codepipeline-user-guide#6]
This page mentions two steps to get started:
https://github.com/awsdocs/aws-codepipeline-user-guide/blob/master/doc_source/detect-state-changes-cloudwatch-events.md

```
Complete the CloudWatch Events prerequisites. For information, see Amazon CloudWatch Events Prerequisites.
Familiarize yourself with events, rules, and targets in CloudWatch Events. For more information, see What Is Amazon CloudWatch Events.
```

However clicking the link "Amazon CloudWatch Events Prerequisites" directs the visitor to the "What Is Amazon CloudWatch Events" page. So these two steps should be combined.

**Comment by darlaker** [comment]
Thank you so much for your feedback on this content. We appreciate you bringing this to our attention. Will research and then determine whether the link should be updated, and if not, will combine these steps to correct the issue as recommended.

**Comment by darlaker** [comment]
Hello @mb-dev, This was a broken (and mis-named) cross-reference to what should have been this "Regional Endpoints" section of the CloudFormation User Guide: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/GettingSetup_cwe.html#CWE_Prerequisites  

The broken link has now been corrected in the CodePipeline User Guide. The corrected markdown files have been pushed to the repository. Thank you again for your feedback!

**Comment by mb-dev** [comment]
Great. closing this then.
