### ISSUE TITLE
Inaccurate information for AWS GovCloud (US-West) and source actions

### ISSUE THREAD

**Issue by vahobrsti** [awsdocs/aws-codepipeline-user-guide#60]
As stated by documentation[1]: 

```
Source Actions:

   *  Amazon ECR

   *  AWS CodeStar Source Connection (Bitbucket)

   *  AWS CodeStar Source Connection (GitHub)

    * AWS CodeStar Source Connection (GitHub Enterprise Server)

    * GitHub
```

This is inaccurate. The right options are: 

```
  * CodeCommit 
  * ECR
  * S3
  * Github (Version 1)
```

Please reflect the right information in the docs for CodePipeline. Thanks 

[1] AWS CodePipeline - How AWS CodePipeline Differs for AWS GovCloud (US) - https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-acp.html#govcloud-acp-diffs

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
