### ISSUE TITLE
Minor: empty notes in integrations-action-type.md

### ISSUE THREAD

**Issue by russau** [awsdocs/aws-codepipeline-user-guide#62]
On the docs page [Integrations with CodePipeline action types
](https://docs.aws.amazon.com/codepipeline/latest/userguide/integrations-action-type.html) I see empty notes under the titles for: 

* AWS Device Farm test actions https://github.com/awsdocs/aws-codepipeline-user-guide/blob/9342ae/doc_source/integrations-action-type.md?plain=1#L136
* AWS CloudFormation deploy actions https://github.com/awsdocs/aws-codepipeline-user-guide/blob/9342ae/doc_source/integrations-action-type.md?plain=1#L211
* Snyk invoke actions https://github.com/awsdocs/aws-codepipeline-user-guide/blob/9342ae/doc_source/integrations-action-type.md?plain=1#L305

I don't think this is intentional?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
