### ISSUE TITLE
Default of PollSourceForChanges is not clear in the documentation.

### ISSUE THREAD

**Issue by scholtenmartijn** [awsdocs/aws-codepipeline-user-guide#8]
After searching through the documentation it's hard to figure out what the default of the value PollSourceForChanges is. The only documentation that mentions something about the default is:

> For pipelines created or updated using the CLI, this parameter defaults to true, but this is not the recommended configuration. Instead, update your pipeline to use the recommended change-detection method and then set this parameter to false.
https://github.com/awsdocs/aws-codepipeline-user-guide/blob/master/doc_source/run-automatically-polling.md

Can this be clearer in the documentation? Creating a Codepipeline through Cloudformation and using a webhook for example to use as a change detection method, the Codepipeline might end up triggering twice when the PollSourceForChanges is left out defaulting back to True.

**Comment by darlaker** [comment]
Thank you for taking the time to provide this feedback. We will update the change detection procedures to clarify the PollForSourceChanges defaults. Will update this table that points to procedures to disable polling and add a webhook: https://docs.aws.amazon.com/codepipeline/latest/userguide/update-change-detection.html

**Comment by darlaker** [comment]
Thank you again for this feedback on the User Guide. The default setting information for the PollForSourceChanges parameter has been provided in a table with examples. The updated table can be viewed here: https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#PollForSourceChanges-defaults

Added a note to the CLI and CloudFormation change detection procedures with a description to enter/set the parameter to false to avoid the pipeline triggering more than once: 
https://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-webhooks-create.html
https://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-webhooks-create-cfn.html
